orbs:
  slack: circleci/slack@4.4.4

workflows:
  version: 2
  test_workflow:
    jobs:
     - test
    #  - notify
     - push:
          requires:
            - test
          filters:
            branches: 
              only: main, dev 
            tags: 
              only: '\d{1,2}\.\d{1,2}\.\d{1,2}'

jobs:
  test:
   docker:
    - image: circleci/golang:1.15.8
   steps:
    - checkout
    - run: gofmt -e main.go

  # notify:
  #   docker: 
  #     - image: cimg/base
  #   steps: 
  #     - slack/notify:
  #        event: fail
  
  push:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login to Dockerhub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Building image
          command: docker build -t $DOCKERHUB_USERNAME/test-01:latest .
      - run:
          name: Pushing to Dockerhub
          command: docker push $DOCKERHUB_USERNAME/test-01:lates
      
