version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run: gofmt -e main.go
      - run:
          name: Slack notifications
          command: >
            curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed pipeline, andrew-ito/test-01"}' https://hooks.slack.com/services/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
          when: on_fail  
  push:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKiN
          # command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          # command: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
      - run:
          name: Build
          command: docker build -t $DOCKERHUB_USERNAME/task-01:latest .
      - run:
          name: Push
          command: docker push $DOCKERHUB_USERNAME/task-01:latest
      - run:
          name: Slack notifications
          command: $CURL_FUNC
          when: on_fail

workflows:
  circle-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - push:
          requires:
            - test
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}