
# orbs:
#   slack: circleci/slack@4.10.1

workflows:
  version: 2
  test_workflow:
    jobs:
     - test
     - push:
          requires:
            - test
          filters:
            branches: 
              only: main, dev 
            tags: 
              only: '\d{1,2}\.\d{1,2}\.\d{1,2}'

jobs:
  test:
   docker:
    - image: circleci/golang:1.15.8
   steps:
    - checkout
    - run: gofmt -e main.go

  push:
    docker:
      image: circleci/ubuntu-server
    steps:
      - checkout
      - run:
          name: Login
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - run:
          name: Build
          command: docker build -t $DOCKERHUB_USERNAME/task-01:latest .
      - run:
          name: Push
          command: docker push $DOCKERHUB_USERNAME/task-01:lates
  # notify:
  #  docker: 
  #      - image: cimg/base:stable
  #  steps: 
  #   - slack/notify:
  #       event: fail
  #       template: basic_fail_1
  #       webhook: $SLACK_WEBHOOK


      
