#slack-fail-post-step: &slack-fail-post-step
#  post-steps:
#    - slack/status:
#        fail_only: true
#orbs:
#  slack: circleci/slack@4.9.3

workflows:
  version: 2
  test_workflow:
    jobs:
     - test
     - build:
          requires:
           - test
     - push:
          requires:
            - build
          filters:
            branches: 
              only: main, dev 
            tags: 
              only: '\d{1,2}\.\d{1,2}\.\d{1,2}'

jobs:
  test:
   docker:
    - image: cimg/base:stable 
    - image: cimg/go:stable
   steps:
    - checkout
    - run: gofmt -e main.go


  build: 
     docker:
      - image: cimg/base:stable
      - image: cimg/go:stable
     requires: 
      test
     steps: go build -o main main.go
  
  push:
    docker: 
      -image: cimg/base:stable
    steps: 
      - checkout
      
