version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  test:
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run: gofmt -e main.go
      # - run:
      #     name: Slack notifications
      #     # command: >
      #     #   curl -X POST -H 'Content-type: application/json' --data '{"text":"Failed pipeline, marina1327/task-01"}' https://hooks.slack.com/services/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
      #     # when: on_fail  
  push:
    docker:
      - image: 'cimge/base:stable'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker
          command: |
            docker build -t $DOCKERHUB_USERNAME/task-01:latest .
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/task-01:latest
      - slack/notify:
          event: fail
          template: basic_fail_1


  # notify:
  #   docker:
  #     - image: 'cimg/base:stable'
  #       auth:
  #         username: marina1327
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - slack/notify:
  #         event: fail
  #         template: basic_fail_1
  #         custom: |
  #           {
  #             "blocks": [
  #               {
  #                 "type": "section",
  #                 "fields": [
  #                   {
  #                     "type": "plain_text",
  #                     "text": "*Failed push event*",
  #                     "emoji": true
  #                   }
  #                 ]
  #               }
  #             ]
  #           }
          
workflows:
  circle-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      - push:
          requires:
            - test
          context: slack-secrets
          filters:
            branches:
              only:
                - main
                - dev
            tags:
              only:
                - \d{1,2}\.\d{1,2}\.\d{1,2}
      # - notify:
      #     context: slack-secrets
      #     requires:
      #       - push