name: myci
    
on: 
  push:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
  pull_request:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
      
jobs: 
  test: 
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
    
      - name: validate
        run: gofmt -e main.go
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t "task-01:latest" .
      - name: push  
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-01:latest
        

      
 

        
   
        
          
