name: myci
    
on: 
  push:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
  pull_request:
    branches: [ "main" , "dev" ]
    tags: 
      - '\d{1,2}\.\d{1,2}\.\d{1,2}'
      
jobs: 
  test: 
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
    
      - name: validate
        run: gofmt -e main.go
        
      - name: ifs
        run: |
          if ${{ secrets.COMMIT_BRANCH == secrets.DEFAULT_BRANCH }}; then
            tag=""
              echo "Running on default branch ${{ secrets.DEFAULT_BRANCH }}: tag = 'latest'"
          else
            tag=":${{ github.sha }}"
              echo "Running on branch ${{ secrets.COMMIT_BRANCH }}: tag = ${{ github.sha }}
          fi    
  
  build:
    runs-on: ubuntu-latest
    needs: test
    steps: 
      - name: Copy file
        uses: actions/checkout@v1
      - name: Login 
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: docker build -t "task-01:latest" .
      - name: push  
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-01:latest
        

      
 

        
   
        
          
